services:
  newsletter:
    build: .
    container_name: newsletter
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - observability
    volumes:
      - ./db/newsletter.sqlite:/app/db/newsletter.sqlite

networks:
  observability:
    external: true
